### ISSUE TITLE
Serial communication

### ISSUE THREAD

**Issue by fjp** [mktk1117/six_wheel_robot#1]
Hi, thank you for providing such a great project! 
This is not an issue but I am interested why you used serial communication between Raspberry Pi and Arduino?
Is there a specific reason you did not use [rosserial_arduino](http://wiki.ros.org/rosserial_arduino) to setup a ros node on the Arduino?

**Comment by mktk1117** [comment]
Hi, thank you for your comment!
Actually, it is a simple reason. I didn't notice the `rosserial_arduino` at that moment.
Now, I think it would be cleaner to use rosserial as you suggest.
