### ISSUE TITLE
Rostopic echo /arduino doesn't print anything

### ISSUE THREAD

**Issue by prasuchit** [mktk1117/six_wheel_robot#2]
Hi, this is a very useful project. I'm currently trying to replicate it and test it on just one motor on the arduino code side. So I have commented out only the lines that assign values to the motor in the arduino code and I'm trying to run it. I see the values being printed on the motordriver.py window, but when I do rostopic echo /arduino, nothing is being printed and my motor isn't running either.

My rostopic list shows arduino topic. Kindly help.

**Comment by mktk1117** [comment]
Hi, thank you for your interest.
Could you get messages from Arduino with serial?
The values printed on the motordriver.py is no the message from Arduino and they can be printed without connecting to it.

I think your first step is making sure Arduino and raspberry pi are surely connected.
Please check this page, [Communication-between-Arduino-and-Raspberry-Pi](https://github.com/mktk1117/six_wheel_robot/wiki/Communication-between-Arduino-and-Raspberry-Pi)
